config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: "home#index"
  resources :bicycles
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bicycle.rb
require 'telegram/bot'

class Bicycle < ApplicationRecord
  has_one_attached :image
  has_many :visits
  validates :model, :style, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def self.filter(model, style, min_price, max_price)
    style == "all" ? style = nil : style
    
    return where("model LIKE ? AND style = ? AND price >= ? AND price <= ? ", "%#{model}%", style, min_price, max_price) if !model.empty? && style && !min_price.empty? && !max_price.empty?
    return where("model LIKE ? AND style = ? AND price >= ? ", "%#{model}%", style, min_price) if !model.empty? && style && !min_price.empty?
    return where("model LIKE ? AND style = ? AND price <= ? ", "%#{model}%", style, max_price) if !model.empty? && style && !max_price.empty?
    return where("model LIKE ? AND price >= ? AND price <= ? ", "%#{model}%", min_price, max_price) if !model.empty? && !min_price.empty? && !max_price.empty?
    return where("model LIKE ? AND style = ? ", "%#{model}%", style) if !model.empty? && style
    return where("model LIKE ? AND price >= ? ", "%#{model}%", min_price) if !model.empty? && !min_price.empty?
    return where("model LIKE ? AND price <= ? ", "%#{model}%", max_price) if !model.empty? && !max_price.empty?
    return where("style = ? AND price >= ? AND price <= ?", style, min_price, max_price) if style && !min_price.empty? && !max_price.empty?
    return where("style = ? AND price >= ?", style, min_price) if style && !min_price.empty?
    return where("style = ? AND price <= ?", style, max_price) if style && !max_price.empty?
    return where("model LIKE ?", "%#{model}%") if !model.empty?
    return where(style: style) if style
    return where("price >= ? AND price <= ?", min_price, max_price) if !min_price.empty? && !max_price.empty?
    return where("price >= ?", min_price) if !min_price.empty?
    return where("price <= ?", max_price) if !max_price.empty?
    return Bicycle.all
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visits
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
  has_one :user
  has_one :bicycle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show]
  def index
    @bicycles = Bicycle.all
    if params[:model] || params[:style] || params[:price_min_bound] || params[:price_max_bound]
      @bicycles = Bicycle.filter(params[:model], params[:style], params[:price_min_bound], params[:price_max_bound])
    else
      @bicycles = Bicycle.all
    end
  end

  def show
    @bicycle = Bicycle.find(params[:id])
    @visit = Visit.create!(user: current_user, bicycle: @bicycle)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/styles_helper.rb
module StylesHelper
  def all_styles
    styles = ["all"]
    Bicycle.all.each do |bicycle|
      styles << bicycle.style if !styles.include?(bicycle.style)
    end
    styles
  end
end

app/views/bicycles/index.html.erb
<div class="flex justify-between">
  <div class="flex flex-col pl-6">
    <% @bicycles.each do |bicycle| %>
      <a href="<%= bicycle_url(bicycle) %>" class="flex border-2 border-black rounded-md w-1/2 mb-4 pl-3">
        <div class="flex w-1/3"><%= image_tag(bicycle.image) if bicycle.image %></div>
        <div class="fond-bold text-lg pl-3">
          <div>Model : <%= bicycle.model.capitalize %></div>
          <div>Style : <%= bicycle.style.capitalize %></div>
          <div>Price : <%= bicycle.price.round(2) %>$</div>
          <div>Visits : <%= bicycle.visits.count %></div>
        </div>
      </a>
    <% end %>
  </div>

  <form class="flex flex-col justify-start">
    <%= form_with url: "/bicycles", method: :get do |form| %>
      <div class="flex flex-row">
        <%= form.label :model, "Model:", class: "font-bold text-xl pr-2" %>
        <%= form.text_field :model, class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300
                                            rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700
                                            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>
      <div class="flex flex-row">
        <%= form.label :style, "Style:", class: "font-bold text-xl pr-2" %>
        <%= form.select :style, all_styles, class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300
                                                    rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700
                                                    dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>
      <div class="flex flex-row">
        <%= form.label :price_min_bound, "Minimum price: ", class: "font-bold text-xl pr-2" %>
        <%= form.number_field :price_min_bound, class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300
                                            rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700
                                            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>
      <div class="flex flex-row">
        <%= form.label :price_max_bound, "Maximum price: ", class: "font-bold text-xl pr-2" %>
        <%= form.number_field :price_max_bound, class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300
                                            rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700
                                            dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
      </div>
      <%= form.submit "Filter" %>
    <% end %>
  </form>
</div>

app/views/bicycles/show.html.erb
<div class="flex flex-col justify-center items-center w-full">
  <h3 class="font-bold text-3xl">About the <%= @bicycle.model %></h3>
  <p class= "font-bold text-lg"><%= @bicycle.description %>
  <section class="flex flex-row justify-around w-2/3">
    <div class="w-1/2 h-1/2"><%= image_tag(@bicycle.image) if @bicycle.image %></div>
    <div class="justify-center items-center pl-4 pt-10">
      <div class= "font-bold text-lg">Style: <%= @bicycle.style.capitalize %></div>
      <div class= "font-bold text-lg">Color: <%= @bicycle.color.capitalize %></div>
      <div class= "font-bold text-lg">Price: <%= @bicycle.price.round(2) %>$</div>
    </div>
  <section>
</div>

app/views/home/index.html.erb
<div class="flex flex-col justify-center items-center">
  <a href="<%= bicycles_path %>" class="flex flex-col justify-center items-center w-1/4 rounded-xl mt-20 bg-green-500">
    <h4 class="flex mt-10 font-bold text-4xl text-white">Start cycling now!</h4>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlexCycle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <header class ="flex flex-row justify-between w-full h-1/3 py-6 bg-validera-darker">
        <h1 class="flex flex-col items-start pl-4 font-bold text-6xl text-white">Alex Cycle</h1>
        <div class="flex justify-center items-center font-bold text-3xl"><%= link_to 'Sign out',
                    destroy_user_session_path, method: :get, class: "font-bold text-3xl text-validera-darker" if current_user %></div>
        <div class="flex justify-center items-center font-bold text-3xl"><%= link_to 'Sign in',
                    user_session_path, method: :post, class: "text-validera-darker" unless current_user %></div>
      </header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>